# Generated by Django 3.2.10 on 2022-10-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientslist',
            name='last_payment',
            field=models.DateTimeField(verbose_name='Last payment'),
        ),
        migrations.AlterField(
            model_name='clientslist',
            name='lastcall_date',
            field=models.DateTimeField(verbose_name='Last call'),
        ),
        migrations.AlterField(
            model_name='clientslist',
            name='reg_date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
