# Generated by Django 3.2.10 on 2022-10-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_activepaymentclients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivePaymentClients',
        ),
    ]
