# Generated by Django 3.2.10 on 2022-10-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20221007_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientsList',
        ),
        migrations.DeleteModel(
            name='NotActiveClientsList',
        ),
        migrations.DeleteModel(
            name='NotActivePositiveBalance',
        ),
    ]
