# Generated by Django 3.2.10 on 2022-10-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_clientslist_notactiveclientslist_notactivepositivebalance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotActiveClientsList',
            new_name='NoActiveClientsList',
        ),
    ]
